### ISSUE TITLE
plus de mise à jour des températures

### ISSUE THREAD

**Issue by lennvilardi** [mika-nt28/Jeedom-Eibd#122]
Bonjour, 
Depuis le 25/11, je n'ai plus de màj des températures, si je fais un read puis tester la valeur remonte.
Je viens d'installer la dernière version du github e5628f53e97be75505a05ab153d21a468c723a28.
Merci d'avance

**Comment by mika-nt28** [comment]
Je doute que cela proviennent d'un bug du plugin.
Est ce que tes log sont en mode debug?
C'est la première chose a faire afin de retrouvé une éventuelle trace de ce d'un passage sur le bus.
Tu peux aussi scruter le bus monitor de jeedom pour voir s'il voit passé un message de tes thermostat
Derniere chose que tu peux verifié c'est la repetivité des commande sur jeedom

**Comment by mika-nt28** [comment]
Vue dans le forum a continué sur le poste
