### ISSUE TITLE
Le demon s'arrête après une panne d'électricité

### ISSUE THREAD

**Issue by achailleux** [mika-nt28/Jeedom-Eibd#142]
Bonjour,

Nous avons eu plusieurs pannes d'électricité ces derniers jours et j'ai pu constater que le demon du plug-in Eibd ne redémarrait pas après le redémarrage de la Jeedom. Il a fallu à chaque fois que je la rallume à la main.
Etes-vous au courant du problème ?

Merci par avance,

Alexandre

**Comment by mika-nt28** [comment]
Chez moi le deamon se relance bien tout seul.
Ce n'est d’ailleurs pas le plugin qui relance sont deamon tout seul mais c'est jeedom qui gere.
Est ce que la gestion automatique est bien activé?
