### ISSUE TITLE
Dit manquants pour les gateway dali compatible DT8

### ISSUE THREAD

**Issue by caplam** [mika-nt28/Jeedom-Eibd#143]
Température de blanc (pour les leds tunable white): DPT 7.600: 2 octets non signés : température de couleur en K
DPT 251.600: pour valeur rgbw 6 octets combinés. 
octet de poids faible :  W (0-100%)
                                       B (0-100%)
                                       G (0-100%)
                                       R (0-100%)
                                       mW (0,1) validation de la valeur dans le champ W
                                       mB (0,1) validation de la valeur dans le champ B
                                       mG (0,1) validation de la valeur dans le champ G
                                       mR (0,1) validation de la valeur dans le champ R
                                       12 bits sans signification
On peut aussi ajouter le dit 242.600 pour utiliser l'espace colorimétrique X,Y. Ce dpt est encodé sur 6 octets.
Une couleur peut être repérée par ses coordonnées X,Y avec 0<x<1 et 0<y<1
Pour la représenter avec knx on utilise 6 octets:
octet de poids faible : la luminosité entre 0 et 100%
puis Y sur 2 octets (0-65535) 65535=1
puis X sur 2 octets (0-65535) 65535=1
puis 1 bit pour indiquer la validité de la luminosité
puis 1 bit pour indiquer la validité de XY
Les autres bits ne sont pas significatifs.

**Comment by mika-nt28** [comment]
le dpt 7.xxx existe deja, tu peux l'utilisé a la pace du DPT 7.600.
La deference est les paramertrage automatique des valeurs et unité.
Je l'ai integrer comme ca
"Name"=>"Température de blanc",
"Valeurs"=>array(),
"min"=>0,
"max"=>65535,
"InfoType"=>'numeric',
"ActionType"=>'slider',
"Unite"=>"lx"

**Comment by mika-nt28** [comment]
Pour le RGBW je bloque un peux car jeedom ne gere que HEX donc RGB
