### ISSUE TITLE
Bug volet roulant

### ISSUE THREAD

**Issue by lennvilardi** [mika-nt28/Jeedom-Eibd#177]
Bonjour,
Depuis la màj disponible actuellement à l'action de la commande physique ou dans jeedom, les volets se déplacent de la valeur demandée en boucle descente montée.
La désactivation du plugin a arrêté la boucle et un retour avec un backup plus ancien a résolu le problème.
Je n'ai pas de log disponible

**Comment by mika-nt28** [comment]
Effectivement je travaille sur ce bug
Je pense qu'il provient de la correction de la fonction transmission qui vient d'etre debuger
Il faut deja verifier que se flag soit actif que lorsque l'on veux mettre a jours la valeur sur le bus par rapport a l'etat (Etat qui n'a pas le meme gad voire meme d'autre plugin)

Mettre a jours le plugin qui a eu quelques correction
