### ISSUE TITLE
Souci de BSO

### ISSUE THREAD

**Issue by DomoJe** [mika-nt28/Jeedom-Eibd#199]
Bonjour,

Suite à la dernière série de mises à jour mes BSO utilisant un odule Hager TXA228-a2 ne fonctionnent plus.

Certains de mes BSO sont sur un TXA207B, ceux ci n'ont aucun souci.

Merci d'avance

**Comment by mika-nt28** [comment]
Comment sont il configurer?

**Comment by DomoJe** [comment]
[Config_BSO.pdf](https://github.com/mika-nt28/Jeedom-Eibd/files/2483265/Config_BSO.pdf)

Voila la config d'un des BSO
Les BSO qui fonctionnent on une configuration identique (mais ne sont pas sur le meme module Hager)

**Comment by DomoJe** [comment]
[eibd.log](https://github.com/mika-nt28/Jeedom-Eibd/files/2483293/eibd.log)
Voila le fichier de Log en mode debug en appuyant uniquement sur le bouton "stop" les BSO montent..

**Comment by mika-nt28** [comment]
Je vois que tu as le flag transmetre d'actif
Le retour d'etat de cette commande vien d'ou ?
Si c'est de ton reseau KNX il n'est pas tres recommande de transmettre un état déjà transmis

**Comment by DomoJe** [comment]
Merci pour le conseil,
Tout a l'air de fonctionner maintenant. Bizarrement cette erreur de ma part n'avait aucune incidence en utilisant l'ancienne version.

Merci encore

**Comment by mika-nt28** [comment]
Oui car la fonction transmettre était bug et c'est l'objet de correction des dernière release.
Je te rassure beaucoup dont moi a eu de soucis de se genre
