### ISSUE TITLE
Remonté de la position

### ISSUE THREAD

**Issue by chryss44** [mika-nt28/Jeedom-Eibd#217]

**Comment by chryss44** [comment]
Bonjour Mika, je viens de me rendre compte que e problème n'est pas résolu.
J'ai dans ETS les remontés de position mais ça n'apparait pas dans le Monitor de Jeedom :-(
![capture d ecran 2018-11-25 a 18 29 18](https://user-images.githubusercontent.com/32177747/48982292-ca2baa80-f0e0-11e8-90d3-b5670b9c2d44.png)
![capture d ecran 2018-11-25 a 18 30 17](https://user-images.githubusercontent.com/32177747/48982298-d152b880-f0e0-11e8-9434-a79d22088080.png)
En preview, j'ai téléchargé 2 images (ETS et Monitor) est ce que celle-ci sont visibles ?

**Comment by poluket** [comment]
j'ai le même comportement mais cela n’empêche pas de fonctionner. c'est juste au niveau du moniteur de bus

**Comment by chryss44** [comment]
Oui, peut-être chez toi mais chez moi ça ne met pas à jour les statuts 😔

Christophe

**Comment by mika-nt28** [comment]
Ce que tu veux dire c'est que la valeur ne s'affiche pas

**Comment by mika-nt28** [comment]
Je viens de verifier le code.
Pour que la valeur soit decodé il faut 
* que le bus voit un Write
* que le flag Ecriture soit actif
`elseif($this->Mode == "Write" && $Commande->getConfiguration('FlagWrite'))
	$Message = $Commande->UpdateCommande($this->Data);`

**Comment by mika-nt28** [comment]
J'ai regarder chez moi j'ai des chose similaire mais sur des commande action

**Comment by chryss44** [comment]
Bonjour Mickael,


Voici mes commandes d’un des volets si ça peut t’aider 
Qu’est ce que je peux faire avec le bout de code que tu m’as envoyé ?



Christophe

**Comment by mika-nt28** [comment]
Juste verifier les flag sur les commande

**Comment by chryss44** [comment]
Je regarde dès que je peux, je suis pas chez moi en ce moment.
Je me demande si ça vient pas de ma dernière mise à jour du système sur Raspberry. 

Christophe

**Comment by mika-nt28** [comment]
J'en doute, je pense plus que tu n'as pas autorisé l’écriture et l'update

**Comment by mika-nt28** [comment]
@chryss44 a tu toujours le probleme?

**Comment by mika-nt28** [comment]
Pour que le busmonitor ecrive la valeur du bus dans sa commande nous avons besoin du flag Ecriture
Le flag Lecture est uniquement utilisé pour que jeedom reponde a une requet Read
