### ISSUE TITLE
Selection d'un gad - Aucun retours

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#221]
lorsqu'on clic sur le bouton vert d'une commande, la liste des gad s'affiche mais il n'est pas possible d'en sélectionné un pour l'appliquer sur la commande.

**Comment by mika-nt28** [comment]
Corrigé sur la prochaine beta

**Comment by poluket** [comment]
je confirme que c'est corrigé,  mais il y a un petit problème d'affichage (la ligne disparait) quand je selectionne la ligne, cela se fait une ligne sur 2:
![2018-11-28 13_20_46-eibd - jeedom](https://user-images.githubusercontent.com/43402274/49151563-96cf6280-f310-11e8-90cd-c7be5012845b.png)

**Comment by mika-nt28** [comment]
Oui j'ai ajouté une class qui l'a met en surbrillance mais elle n'a pas l'effet escompté.
Je regarde ca
