### ISSUE TITLE
Mode cyclique ajout des read

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-Eibd#222]

**Comment by mika-nt28** [comment]
Modifié sur la beta

* Reste faire l'update automatiques des commandes lors de la mise a jours

**Comment by poluket** [comment]
donc si je comprends bien, quand c'est une action c'est en write et quand c'est une info c'est en read?

**Comment by mika-nt28** [comment]
C'est bien l'idée

**Comment by poluket** [comment]
proposition:
changer le text explicatif en fonction d'une action ou d'une info.
"lecture cyclique" que pour info
"écriture cyclique" que pour action.

si trop compliqué, bien l'expliquer dans le "?" qui est a coté.
pour le moment, il ne parle pas de la lecture.
