### ISSUE TITLE
inclusion - rafraichissement

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#227]
lorsqu'on active l'inclusion, les nouvelles entrées ne s'affichent pas directement, un champ de recherche se met tout seul dans le champ source
![2018-11-28 13_26_13-eibd - jeedom](https://user-images.githubusercontent.com/43402274/49151819-502e3800-f311-11e8-8906-f199c054d970.png)
si je le supprime, il réaparait. j'ai l'impression que chaque fois qu'une nouvelle entrée est detectée, il le remet.

**Comment by mika-nt28** [comment]
Ha oui je vois
A chaque rafraichissement je met a jours la valeur
