### ISSUE TITLE
Choix de GAD, selection multiple

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#228]
il est possible (dans les 3 onglets) de faire des selections multiples, ce qui peut porter a confusion:
![2018-11-28 13_32_02-eibd - jeedom](https://user-images.githubusercontent.com/43402274/49152128-2c1f2680-f312-11e8-93f1-1baeb55f2bc3.png)
c'est bien la dernière selection qui est pris en compte.

**Comment by mika-nt28** [comment]
Mise a jours
