### ISSUE TITLE
choisir un GAD - filtre

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#229]
le filtre sur le DPT est mis sur la mauvaise colonne (bouton vert dans commande)
![2018-11-28 13_35_22-eibd - jeedom](https://user-images.githubusercontent.com/43402274/49152292-a2bc2400-f312-11e8-82c5-5f6c854a60c9.png)

**Comment by mika-nt28** [comment]
Effectivement
