### ISSUE TITLE
ajout gad inconnu

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#230]
quand on va sur une commande puis bouton vert, on a cette fenetre qui s'ouvre:
![2018-11-28 13_47_13-greenshot](https://user-images.githubusercontent.com/43402274/49152836-4eb23f00-f314-11e8-95b3-236d7eb360f2.png)
et si on clic sur le bouton, on a une autre qui s'ouvre en arrière
![2018-11-28 13_46_40-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/49152857-5bcf2e00-f314-11e8-8f9e-8363f9009c9d.png)

pour moi, il faudrait cacher les 2 boutons lorsqu'on est arrivé via le bouton vert de la commande

**Comment by mika-nt28** [comment]
Ha oui c'est un vestige sa
Je le supprime
