### ISSUE TITLE
amelioration interface "choisir un gad"

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#236]
pour une plus grande  facilité:
- autorisé le redimmentionement de la fenetre et le deplacement
- double clic sur une ligne =  clic + valider
- bouton clear all
- garder le bouton valider toujours visible pour ne pas devoir scroller tout en bas pour valider.
![2018-11-30 14_01_42-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/49290959-d16c0300-f4a8-11e8-887a-e78208a7f860.png)

**Comment by mika-nt28** [comment]
On garde ca en tete

**Comment by mika-nt28** [comment]
Tu a raison de cree une issus avec ses idée
Pour l'instant je veux finir le parser pour etre bien et pas m'eparpillé

**Comment by poluket** [comment]
pour les adresses de groupes, je mettrais les adresses avant les nom, pour moi ce serait plus clair. a tester :)
![2018-11-30 22_26_40-eibd - jeedom](https://user-images.githubusercontent.com/43402274/49315899-7c071480-f4ef-11e8-8e5e-341932183457.png)

**Comment by mika-nt28** [comment]
Ces modifications doivent faire partie de la dernière beta
