### ISSUE TITLE
gad inconnue tous en 1.XXXX

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#237]
identification de tous les gads en 1.xxxx
![2018-11-30 14_01_42-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/49291134-7b4b8f80-f4a9-11e8-9487-8ffebd0d9603.png)

**Comment by mika-nt28** [comment]
Harf oui je l'avais oubilé ce bug

**Comment by poluket** [comment]
c'est pour cela que je l'ai mis ici ;)

**Comment by mika-nt28** [comment]
Corrigé normalement dans la derniere beta
