### ISSUE TITLE
l'inclusion s'active tout seul

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#239]
a  partir du moment ou on ouvre le fenêtre "importer les commandes inconnues", le mode d'inclusion s'active tout seul (mais le bouton garde le string "activer l'inclusion").
quand je clic sur  "activer le mode inclusion", j'ai le message en vert "Vous etes sortie du mode Inclusion".
et si je clic une 2 eme fois, j'ai "désactiver le mode inclusion" (qui lui est correct).

**Comment by mika-nt28** [comment]
Il s'ajoute ou s'affiche
S'il sont enregistrer il s'afficheront

**Comment by poluket** [comment]
ils s'ajoutent. peut importe que le bouton soit activé ou pas, 

j'ai donné acces a mon jeedom si tu veux  essayer. j'ai des données toutes les minutes, il te suffit d'attendre un peu

**Comment by mika-nt28** [comment]
A tu fais la mise a jours de se matin j'avais peut etre pas poussé toute les corrections
Chez moi elle ne s'ajoute plus

**Comment by poluket** [comment]
maintenant, elles ne s'ajoutent plus du tout même quand le bouton est activé.

**Comment by mika-nt28** [comment]
Chez moi j'ai bien des remonté d'info

**Comment by mika-nt28** [comment]
La connexion a ton jeedom de test est elle toujours active?

**Comment by poluket** [comment]
Elle est ouverte

**Comment by mika-nt28** [comment]
Visiblement elle ne fonctionne plus et j'arrive toujours pas a cree un docker en lian a ma database

**Comment by poluket** [comment]
Je te l'ouvre

**Comment by poluket** [comment]
tu devrais avoir acces

**Comment by mika-nt28** [comment]
Normalement corrigé
