### ISSUE TITLE
[Proposition] beta

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#254]
Yep,
suite aux différents tests du **système d'import**, je te propose de mettre en pause la partie de création de modules knx et de regarder pour: 
- la création de l'arborescence adresse de groupe (super utile je trouve)
![2018-12-20 09_27_22-eibd - jeedom](https://user-images.githubusercontent.com/43402274/50272941-915dc780-0439-11e9-8119-c055033795ab.png)
- la liste des équipements
![2018-12-20 09_28_45-eibd - jeedom](https://user-images.githubusercontent.com/43402274/50273029-c538ed00-0439-11e9-8d18-2d48f61111e3.png)
 j'ai encore des problèmes, la liste n'est pas complète. il manque plein de module, c'est p-e suite a une incompatibilité avec mon xml.

**dans les commandes (bouton vert):**
![2018-12-20 09_34_16-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/50273267-7e97c280-043a-11e9-8ff2-e0b2db8b1f36.png)

- parfois, quand on clic sur le bouton vert, la fenêtre "choisir un GAD" ne s'ouvre pas.
pour simuler le problème, tu l'ouvre une fois, tu la ferme (X en haut a droite) et puis tu essayes de la rouvrir, elle ne s'ouvre plus. un F5 est nécessaire pour que cela refonctionne

- dans adresse de groupe, il n'est plus possible de sélectionner un GAD, il ne devient plus BOLD et n'est plus ajouté a la commande quand on clic sur valider  
![2018-12-20 09_35_50-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/50273354-ba328c80-043a-11e9-837d-1d0a54796f8f.png)

- est ce possible d'avoir 3 couleurs différentes pour les GAD:
=> p-e bleue si le gad est compatible au DTP de la commande
=> p-e rouge si le gad n'est pas compatible au DTP de la commande (mais toujours laisser la possibilité de le selectionner).
=> p-e noir si pas de DTP configuré

- donner la possibilité de redimensionner la fenêtre, je trouve cela mieux quand on peut la redimensionner comme l'on veux (comme pour "importer les gads inconnues"). 

- s’arranger pour que le bouton valider soit toujours visible. quand il y a beaucoup de gad, le bouton est tout en bas, il faut scroller beaucoup (p-e le mettre au dessus?)

**Pour l'ajout d'un équipement avec template:**
- p-e indiquer les DTP attendu pour chaque valeur
![2018-12-20 09_53_27-eibd - jeedom](https://user-images.githubusercontent.com/43402274/50274412-7ee58d00-043d-11e9-990d-f8d048e771c9.png)

- p-e regrouper les commandes ayant le même GAD ensemble
![2018-12-20 09_53_27b-eibd - jeedom](https://user-images.githubusercontent.com/43402274/50274629-f9aea800-043d-11e9-8876-af0b4fa05847.png)
ce serra plus simple et plus rapide de créer via template.

ce sont des idées qui me passent comme cela et des erreurs vues :)

fait ton choix (j'ouvre mon serveur de test maintenant si tu veux regarder)

**Comment by mika-nt28** [comment]
Est ce que tu peux refaire chaque élément dans des issus différent
Ca facilitera le suivie et mes avancement

**Comment by mika-nt28** [comment]
Ses points sont normalement corrigé
* parfois, quand on clic sur le bouton vert, la fenêtre "choisir un GAD" ne s'ouvre pas.
pour simuler le problème, tu l'ouvre une fois, tu la ferme (X en haut a droite) et puis tu essayes de la rouvrir, elle ne s'ouvre plus. un F5 est nécessaire pour que cela refonctionne

* dans adresse de groupe, il n'est plus possible de sélectionner un GAD, il ne devient plus BOLD et n'est plus ajouté a la commande quand on clic sur valider
