### ISSUE TITLE
[BUG] problème d'onglet dans "Choisir un Gad"

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#257]
pour le simuler:
ouvrir "Importer les commandes inconnue" puis le fermer directement.
aller dans un module (par exemple lampe 2), onglet commande et cliquer sur un bouton vert des GAD.
Il n'est pas possible de changer d'onglet dans la fenetre qui vient de s'ouvrir sans faire un F5. On reste avec les commandes inconnues

**Comment by mika-nt28** [comment]
Correction directement sur ta machine de test et reportée sur la beta
