### ISSUE TITLE
[Rafraichissement] Inclusion

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#268]
Quand on active l'inclusion, rien n’apparaît mais si l'on ferme la fenêtre et que l'on l'ouvre de nouveau, les nouvelles entrées sont bien là.

le moteur fonctionne bien mais il n'y a pas de rafraîchissement sur la page ouverte.

**Comment by mika-nt28** [comment]
Normalement il y a un rafraichissement toute les 10s

**Comment by mika-nt28** [comment]
Corrigé

**Comment by poluket** [comment]
ok, mais j'ai toujours le problème de rafraichissement

**Comment by mika-nt28** [comment]
Effectivement j'ai trouvé le bug sur le rafraîchissement.
C'est corrigé
