### ISSUE TITLE
[BUG] Import Projet KNX

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#269]
pour tester, j'ai importer ton projet KNX "template". jusque la, aucun problème.
puis j'ai importer mon projet KNX et la dans l'onglet adresse de groupe, les GAD des tes templates sont toujours la en + des nouveaux.
![2019-01-24 21_50_57-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/51707794-68c18280-2022-11e9-8ce8-67ba52f6c229.png)

p-e prévoir un clean-up avant d'importer un nouveau

**Comment by poluket** [comment]
après avoir fermé et ouvert de nouveaux la fenêtre, ton Template est parti :)
C'est juste temporaire après l'import d'un autre projet KNX

**Comment by mika-nt28** [comment]
Oui c'est un bug de version intermediaire qui ne doit plus etre present maintenant
