### ISSUE TITLE
[Amélioration] adresse de groupe

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#270]
je propose d’afficher le numéro de groupe principaux et médians de manière a trier la liste dessus.
cela permettrait d'avoir une symétrie au projet ETS

![2019-01-24 21_50_57-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/51708155-6f9cc500-2023-11e9-8274-980cb5b3893a.png)

**Comment by mika-nt28** [comment]
C'est assez compliqué a faire car le gad n’appairait qu'au dernier level.
Il faudrait donc remonté l'information pour la splité

Je la garde pour plus tard s'il y a beaucoup de demande
