### ISSUE TITLE
[BUG] Couleur Bleue - Choisir un GAD

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#272]
![2019-01-24 22_36_05-eib - knx - jeedom](https://user-images.githubusercontent.com/43402274/51710139-7a0d8d80-2028-11e9-87dd-46629facd5ea.png)

- Prévoir une couleur plus douce pour le bleu
- dans mon Screenshots, normalement, tous mes GADs devraient être bleu.
- p-e prévoir une légende pour les couleurs.

**Comment by mika-nt28** [comment]
Alors pour l'instant je souligne en bleu uniquement les gad  avec une DPT identique a celui rechercher
Faut que j'ajoute une autre couleur pour les gad compatible

Sur la dernière version j'ai passé la couleur du texte en blanc pour que ce soit plus lisible

**Comment by poluket** [comment]
ok, super, attention que normalement, tous mes GAD en 1/1/* sont des gad avec un DTP 1.xxxx et donc devraient être aussi en couleur.

**Comment by poluket** [comment]
en cherchant un peu, je me demande si c'est pas a cause du fait que je n'ai pas tous les Equipements lors de l'importation et donc, on ne sais pas faire le lien entre le DTP et un GAD

**Comment by mika-nt28** [comment]
Le template vas plutot definir en 1.001
Je vais mettre une autre couleur pour les DPT 1.xxx mais c'est plus complexe qu'une simple comparaison

**Comment by mika-nt28** [comment]
Est ce que tu pourrais recharger le projet, pour que je complete cette fonction

**Comment by mika-nt28** [comment]
J'ai ajouté la couleur Jaune pour les dpt compatible

**Comment by poluket** [comment]
projet importé

**Comment by mika-nt28** [comment]
Ok, je suis allez voir tu as bien les 2 couleurs
Tu me disais dans un precédant poste
> tous mes GAD en 1/1/* sont des gad avec un DTP 1.xxxx
Si je regarde, ce que remonte les GAD non colorisé, le DataPointType remonté par le parser est "-000", donc je pense non configurer dans le projet ETS.

Je clos donc aussi cette issue, peux tu verifier si dans ton projet ETS tu as bien configurer le DPT sur ses GAD
