### ISSUE TITLE
[BUG] "importe projet KNX" not OK

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#276]
plus d'effet quand on clic sur le bouton, rien ne s'ouvre
![2019-01-25 14_28_16-eibd - jeedom](https://user-images.githubusercontent.com/43402274/51748714-8e479e00-20ad-11e9-9bda-ac11072f5edc.png)

**Comment by mika-nt28** [comment]
Bug corrigé

**Comment by poluket** [comment]
ok

**Comment by poluket** [comment]
Je viens d'importer mon projet

Et j'ai fermé qqs incidents.

A mon avis, il y a encore une petite incompatibilité entre mon 0.xml et le
plugin. Tous les équipements ne sont pas importé



Le ven. 25 janv. 2019 à 15:18, Halbout Michael <notifications@github.com> a
écrit :
