### ISSUE TITLE
Moniteur de bus - affichage

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#309]
La typo des lignes est super grande. Ce qui rend difficile l'affichage de plusieurs lignes.

**Comment by mika-nt28** [comment]
Oui malheureusement cela ne vient pas de moi je n'y ai rien en style.
C'est donc du a une mise a jours du core que je n'ai pas identifié

**Comment by mika-nt28** [comment]
En fait si j'ai trouvé le bug

**Comment by poluket** [comment]
validé en Beta :) merci
