### ISSUE TITLE
NTP / Template

### ISSUE THREAD

**Issue by poluket** [mika-nt28/Jeedom-Eibd#323]
Je suis en train de faire le tour des templates. 
Pour celui du NTP, il ne faudrait pas retirer les 2 commandes infos, avec ton nouveau systeme de lecture/ecriture cyclique? je vois plus le besoin.
Les commandes actions envoient de manière régulière la valeur. 
Mais par contre, elles ne répondent pas a un read.

**Comment by mika-nt28** [comment]
Oui mais bon est ce que ca vaux le coup de les supprimé
Par contre il faudrait que j'ajoute le paramètre cyclique et le flag initialisation
