### ISSUE TITLE
Problème en récupérant la commande ActiveEnergy

### ISSUE THREAD

**Issue by NHanser** [mika-nt28/Jeedom-Eibd#39]
Dans le fichier core/dpt.class.php, 
Lignes 436/437, remplacer
`$ActiveElectricalEnergy=split('|',$option["ActiveElectricalEnergy"]);`

par

`$ActiveElectricalEnergy=explode('|',$option["ActiveElectricalEnergy"]);`

split est déprécié et doit être remplacé par explode. La commande ne fonctionne pas sinon

**Comment by mika-nt28** [comment]
Ha ou c'est vrai je l'oublie souvant.
J'ai mis a jours sur la derniere beta
