### ISSUE TITLE
Problème d'utilisation de la fonction explode

### ISSUE THREAD

**Issue by NHanser** [mika-nt28/Jeedom-Eibd#40]
Suite à l'Issue#39, j'ai remarqué une erreur dans l'utilisation de la fonction "explode"

core/class/eibd.class.php : line 469
`switch(explode($dpt,'.')[0]){`
à remplacer par
`switch(explode('.',$dpt)[0]){`

**Comment by mika-nt28** [comment]
Modification faite sur la beta
