### ISSUE TITLE
L'intiatlisation en envoyant un READ n'est jamais effectuée

### ISSUE THREAD

**Issue by slobberbone** [mika-nt28/Jeedom-Eibd#442]
Lorsque l'on enregistre une commande avec l'option "Initialiser" cochée, aucun read n'est envoyé et la commande ne retourne aucune information. Si on appuie sur le bouton READ, la commande retourne une information.

**Comment by slobberbone** [comment]
Bonjour, @mika-nt28 puis-je savoir pourquoi tu as fermé cette issue ? Est-ce résolu, issue en double ?
Merci pour ton retour

**Comment by mika-nt28** [comment]
Non tu ne peux pas savoir

**Comment by slobberbone** [comment]
Tu veux dire que ce n'est pas un bug ?
