### ISSUE TITLE
Problème de compatibilité avec la dernière version de knxd

### ISSUE THREAD

**Issue by fdubuisson** [mika-nt28/Jeedom-Eibd#83]
La version 0.14.18 de knxd récupérée par le plugin apporte plusieurs incompatibilités;
- l'utilisation de certains modes de connexion tel que ipt/iptn échoue à cause d'un paramètre manquant (--client-addrs=X.X.X:X)
- knxd est installé par défaut en tant que service systemd et le port 6720 se retrouve alloué par défaut au process 'init (1)' de linux, ce qui empêche son utilisation lors du lancement de knxd par le plugin.

**Comment by mika-nt28** [comment]
Est tu sur qu'il est nécessaire ce paramètre (--client-addrs) puisque l'on impose une adresse physique

Normalement a la fin du script d'installation de knx je supprime l'init par systemd mais j'ai vue des message d'erreur alors j'ai peut etre fait de mauvaise modif

**Comment by fdubuisson** [comment]
Le paramètre est indispensable dans le cas ipt ou iptn (j'ai fait pleins de tests donc je n'ai plus la config exacte).
Sans lui, j'avais un message d'erreur de knxd, me disant justement de le rajouter. C'est d'ailleurs confirmé dans la doc [Migrating to 0.12](https://github.com/knxd/knxd/blob/5e707fdb7430009a299d3ad849aecf9ccbc8fdf6/README.md#migrating-to-012)

Concernant l'init, je n'ai pas vérifié les logs d'install; juste vu que le démarrage de knxd par le plugin échouait avec une erreur "port already used". Le fait de faire un 'systemctl service knxd stop' a résolu le problème (jusqu'au prochain reboot, j'imagine).

**Comment by mika-nt28** [comment]
Ok je peux l'ajouter, mais je suis embeter d'ajouté encore un champs de configuration qui sera compliqué a gerer.
Pense tu que l'on peux le mettre en fixe?

Je vais ajouté au demarage du demon cette ligne
systemctl service knxd stop

**Comment by fdubuisson** [comment]
J'ai peur que cela dépende de la configuration de chacun. Ou alors, spécifier une plage qui a peu de chances d'être utilisée, style 99.99.0:10

**Comment by mika-nt28** [comment]
Je pensais reprendre l'adresse --eibaddr pour le start avec un n a 100

**Comment by fdubuisson** [comment]
Sauf erreur de ma part, le n correspond au nombre de clients qui devraient se connecter à knxd. Dans le cas du plugin, il n'y aurait qu'un client non ?
Donc l'utilisation de l'adresse 'eibaddr' pour le start est possible, même s'il reste un risque minime de conflit (si je donne 0.0.1 en 'eibaddr' et que j'ai un participant sur mon réseau en 0.0.2, par exemple). A mettre dans la faq ?

**Comment by mika-nt28** [comment]
Effectivement j'ai supprimer la desactivation du service.
J'ai ajouté a la mise a jours.
J'ai egalement ajouté un champs de configuration du nombre de connexion autorisé (par defaut 1) ainsi que le parametre  --client-addrs
J'ai fait la mise a jours de mon knxd il a l'aire d'avoir démarrer
