### ISSUE TITLE
Erreur de configuration du mode manuel

### ISSUE THREAD

**Issue by fdubuisson** [mika-nt28/Jeedom-Eibd#86]
Ma configuration actuelle du plugin est:
- interface knxd
- ipt sur 192.168.1.13

Ayant déjà un knxd sur mon réseau, je veux passer en manuel pour que le plugin se connecte directement dessus. Je configure donc:
- interface manuelle
- ip 192.168.1.48

Quand je lance le démon, je vois que la commande suivante est exécutée:
```
eibd --daemon=/var/log/knx.log --pid-file=/var/run/knx.pid --eibaddr=0.0.1 -D -T -S --listen-tcp=6720 ipt:192.168.1.13 
```
et les logs suivants:
```
sudo: eibd: command not found
[2017-10-03 21:12:08][DEBUG] : Lancement du Bus Monitor
[2017-10-03 21:12:08][DEBUG] : Connexion a EIBD sur le serveur 192.168.1.48:6720
```

Il y a visiblement un mélange sur les paramètres de configuration. A l'inverse, lorsque je repasse en knxd, j'ai les logs suivants:
```
[2017-10-03 21:12:08][DEBUG] : Lancement du Bus Monitor
[2017-10-03 21:12:08][DEBUG] : Connexion a EIBD sur le serveur 192.168.1.48:6720
```

**Comment by mika-nt28** [comment]
Je regarde ca, car cela fait longtemps que je n'ai pas utilise ce mode 
Au tout debut de la création du plugin lorsque je tournais encore avec linknx et knxweb

**Comment by mika-nt28** [comment]
J'ai effectivement trouvé le bug
La mise a jours est faite sur le market

**Comment by fdubuisson** [comment]
Testé et validé :)
Bravo pour la réactivité !
