### ISSUE TITLE
Bug affichage sous-type

### ISSUE THREAD

**Issue by Grominet** [mika-nt28/Jeedom-Eibd#89]
Problème remonté via le forum : https://www.jeedom.com/forum/viewtopic.php?p=526802#p526802

Lors du changement de sous-type les champs de valeurs s'affichent de façon aléatoire.
Parfois la liste des sous-types ne change pas de label, parfois les champ min/max n'apparraissent pas mais le titre oui.
Difficile à reproduire si ce n'est de "jouer" à créer/enregistré/changer de type.
Une astuce pour contourner serait de désactiver le sous-type automatique.

Cela n'empêche pas le fonctionnement des fonctions déjà créés, qui s'affichent correctement.

**Comment by mika-nt28** [comment]
Normalement corrigé dans la dernière release
